### ISSUE TITLE
assertClass classes

### ISSUE THREAD

**Issue by jfisher-usgs** [mllg/checkmate#126] opened 2017-11-02 18:52 UTC
Great package, thank you!

By design or perhaps mistakenly, the `assertClass` function doesn't allow for different class types. For example,

```
x <- 5
inherits(x, c("numeric", "character"))  # TRUE
checkmate::testClass(x, c("numeric", "character"))  # FALSE
```

Not that I want to run this particular example in practice, but it's sometimes the case that I'll convert an object to the correct class within the function itself (especially for spatial objects). Anyways, I'll suggest allowing for different class types in the `classes` argument.

**Comment by mllg** [comment] 2018-03-29 22:21
Thanks for the suggestion.

Duplicate of #100 and fixed in d11f3d230bbf79a3be5dbe965d0a2c17c7b0ca33.

**Closed by mllg** 2018-03-29 22:21 UTC
